language: php

php:
    - 5.5
    - 5.6
    - 7.0

sudo: true

install:
    - composer self-update
    - composer install

script:
    - ./vendor/bin/phpunit -c tests/phpunit/phpunit.xml --coverage-clover build/logs/clover.xml

after_script:
    - ./vendor/bin/phpspec r -c tests/phpspec/phpspec-travis.yml
    - php ./vendor/bin/coveralls.php -v
